name: CI Pipeline
on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ENVIRONMENT SETUP
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # DEPENDENCY CACHING
      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}

      # LINTING STAGE
      - name: Configure ESLint
        run: |
          npm install eslint --save-dev
          npx eslint --init
        # COMMENT: Auto-configured since no linter present

      - name: Run Linter
        run: npx eslint .
        # QUALITY GATE: Fails on style violations

      # BUILD STAGE
      - name: Build project
        run: docker build -t your_image_name .
        # QUALITY GATE: Fails on build errors

      # TEST STAGE
      - name: Run tests
        run: echo "No tests defined for static web application."
        # QUALITY GATE: No tests to fail

      # DEPLOYMENT STAGE (if evidence found)
      # No deployment steps included as no deployment evidence was found.