name: CI Pipeline
on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ENVIRONMENT SETUP
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # DEPENDENCY CACHING
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      # BUILD STAGE
      - name: Build Docker image
        run: docker-compose build
        # QUALITY GATE: Fails on build errors

      # TEST STAGE
      - name: Run tests
        run: echo "No tests defined for this static web application."
        # QUALITY GATE: No test failures

      # DEPLOYMENT STAGE (if evidence found)
      # No deployment steps included as no deployment evidence was found.