name: CI Pipeline
on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t your-image-name .

      - name: Run Docker container
        run: docker run -d -p 80:80 your-image-name

      - name: Run tests
        run: echo "No tests defined for this static web application."

      - name: Lint HTML and CSS
        run: |
          echo "Linting not configured, please add appropriate linting tools."
          
      - name: Cleanup
        run: docker stop $(docker ps -q --filter ancestor=your-image-name) && docker rm $(docker ps -aq --filter ancestor=your-image-name)