name: CI Pipeline
on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io

      - name: Build Docker image
        run: docker build -t my-static-app .

      - name: Run Docker container
        run: docker run -d -p 80:80 my-static-app

      - name: Check Docker container status
        run: docker ps

      - name: Stop Docker container
        run: docker stop $(docker ps -q)

      - name: Remove Docker image
        run: docker rmi my-static-app